program enBuild;
uses
  Vcl.Forms,
  System.SysUtils,
  Vcl.Controls,
  enSoftMenu in 'enSoftMenu.pas' {frmSoftMenu},
  CTC_UN_M_AVF in 'Movimentacoes\Suprimentos\CTC_UN_M_AVF.pas' {CTC_FM_M_AVF},
  CTC_UN_M_FAC in 'Movimentacoes\Qualidade\CTC_UN_M_FAC.pas' {CTC_FM_M_FAC},
  uValidacoes in '..\enSoftPadrao\Regras\uValidacoes.pas',
  uProxy in '..\enSoftPadrao\Biblioteca\uProxy.pas',
  enConstantes in '..\enSoftPadrao\Padrao\enConstantes.pas',
  PAD_UN_X_PAD in '..\enSoftPadrao\Padrao\PAD_UN_X_PAD.pas' {PAD_FM_X_PAD},
  PAD_UN_X_PSQ in '..\enSoftPadrao\Padrao\PAD_UN_X_PSQ.pas' {PAD_FM_X_PSQ},
  PAD_UN_X_REL in '..\enSoftPadrao\Padrao\PAD_UN_X_REL.pas' {PAD_FM_X_REL},
  Vcl.RecError in '..\enSoftPadrao\Padrao\Vcl.RecError.pas' {ReconcileErrorForm},
  UApplayClassProxy in '..\enSoftPadrao\Biblioteca\UApplayClassProxy.pas',
  enFunc in '..\enSoftPadrao\Padrao\enFunc.pas',
  CAD_UN_C_TAM in '..\enSoftPadrao\Cadastros\CAD_UN_C_TAM.pas' {CAD_FM_C_TAM},
  CAD_UN_C_TIF in '..\enSoftPadrao\Cadastros\CAD_UN_C_TIF.pas' {CAD_FM_C_TIF},
  CAD_UN_C_TME in '..\enSoftPadrao\Cadastros\CAD_UN_C_TME.pas' {CAD_FM_C_TME},
  CAD_UN_C_TRI in '..\enSoftPadrao\Cadastros\CAD_UN_C_TRI.pas' {CAD_FM_C_TRI},
  CAD_UN_C_TXS in '..\enSoftPadrao\Cadastros\CAD_UN_C_TXS.pas' {CAD_FM_C_TXS},
  CAD_UN_C_UND in '..\enSoftPadrao\Cadastros\CAD_UN_C_UND.pas' {CAD_FM_C_UND},
  OFI_UN_C_TIO in '..\enSoftPadrao\Cadastros\OFI_UN_C_TIO.pas' {OFI_FM_C_TIO},
  CTC_UN_C_OBR in 'Cadastros\CTC_UN_C_OBR.pas' {CTC_FM_C_OBR},
  CTC_UN_C_TPR in 'Cadastros\CTC_UN_C_TPR.pas' {CTC_FM_C_TPR},
  CTC_UN_C_EPI in 'Cadastros\CTC_UN_C_EPI.pas' {CTC_FM_C_EPI},
  CTC_UN_R_EPI in 'Relatorios\Cadastros\CTC_UN_R_EPI.pas' {CTC_FM_R_EPI},
  CTC_UN_M_CEP in 'Movimentacoes\Manutencao\CTC_UN_M_CEP.pas' {CTC_FM_M_CEP},
  SEG_UN_X_SEN in 'SEG_UN_X_SEN.pas' {SEG_FM_X_SEN},
  CTC_UN_M_CFE in 'Movimentacoes\Manutencao\CTC_UN_M_CFE.pas' {CTC_FM_M_CFE},
  CTC_UN_M_OFI in 'Movimentacoes\Manutencao\CTC_UN_M_OFI.pas' {CTC_FM_M_OFI},
  SEG_UN_X_BCK in '..\enSoftPadrao\Padrao\SEG_UN_X_BCK.pas' {SEG_FM_X_BCK},
  uDmGeral in '..\enSoftPadrao\DataModule\uDmGeral.pas' {dmGeral: TDataModule},
  CTC_UN_M_BDE in 'Movimentacoes\Manutencao\CTC_UN_M_BDE.pas' {CTC_FM_M_BDE},
  CTC_UN_R_BDE in 'Relatorios\Movimentacoes\CTC_UN_R_BDE.pas' {CTC_FM_R_BDE},
  CTC_UN_M_LOC in 'Movimentacoes\Manutencao\CTC_UN_M_LOC.pas' {CTC_FM_M_LOC},
  CTC_RN_C_OBR in '..\enSoftPadrao\Regras\Build\CTC_RN_C_OBR.pas',
  CTC_RN_C_OFI in '..\enSoftPadrao\Regras\Build\CTC_RN_C_OFI.pas',
  CTC_RN_M_AVF in '..\enSoftPadrao\Regras\Build\CTC_RN_M_AVF.pas',
  CTC_RN_M_BDE in '..\enSoftPadrao\Regras\Build\CTC_RN_M_BDE.pas',
  CTC_RN_M_CEP in '..\enSoftPadrao\Regras\Build\CTC_RN_M_CEP.pas',
  CTC_RN_M_CFE in '..\enSoftPadrao\Regras\Build\CTC_RN_M_CFE.pas',
  CTC_RN_M_FAC in '..\enSoftPadrao\Regras\Build\CTC_RN_M_FAC.pas',
  CTC_RN_M_LOC in '..\enSoftPadrao\Regras\Build\CTC_RN_M_LOC.pas',
  CTC_RN_M_OBR in '..\enSoftPadrao\Regras\Build\CTC_RN_M_OBR.pas',
  CAD_RN_C_ITE in '..\enSoftPadrao\Regras\Cadastros\CAD_RN_C_ITE.pas',
  CAD_RN_C_LOC in '..\enSoftPadrao\Regras\Cadastros\CAD_RN_C_LOC.pas',
  CAD_RN_C_PAR in '..\enSoftPadrao\Regras\Cadastros\CAD_RN_C_PAR.pas',
  CSU_RN_C_FIN in '..\enSoftPadrao\Regras\Cadastros\CSU_RN_C_FIN.pas',
  CMP_RN_M_COT in '..\enSoftPadrao\Regras\Compras\CMP_RN_M_COT.pas',
  CMP_RN_M_PED in '..\enSoftPadrao\Regras\Compras\CMP_RN_M_PED.pas',
  CMP_RN_M_SOL in '..\enSoftPadrao\Regras\Compras\CMP_RN_M_SOL.pas',
  CMP_RN_M_XML in '..\enSoftPadrao\Regras\Compras\CMP_RN_M_XML.pas',
  EST_RN_M_CTE in '..\enSoftPadrao\Regras\Estoque\EST_RN_M_CTE.pas',
  FAT_RN_M_CXA in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_CXA.pas',
  FAT_RN_M_IQM in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_IQM.pas',
  FAT_RN_M_NFE in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_NFE.pas',
  FAT_RN_M_ORC in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_ORC.pas',
  FAT_RN_M_PED in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_PED.pas',
  FAT_RN_M_POS in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_POS.pas',
  FIN_RN_M_BOL in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_BOL.pas',
  FIN_RN_M_CAR in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CAR.pas',
  FIN_RN_M_CHE in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CHE.pas',
  FIN_RN_M_CHE_MOV in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CHE_MOV.pas',
  FIN_RN_M_COB in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_COB.pas',
  FIN_RN_M_CTA_BCO in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CTA_BCO.pas',
  FIN_RN_M_CTA_CXA in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CTA_CXA.pas',
  FIN_RN_M_CXA in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CXA.pas',
  FIN_RN_M_ORC in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_ORC.pas',
  FIN_RN_M_PAG in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_PAG.pas',
  FIN_RN_M_PBX in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_PBX.pas',
  FIN_RN_M_RBX in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_RBX.pas',
  FIN_RN_M_RCR in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_RCR.pas',
  FIN_RN_M_REC in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_REC.pas',
  OFI_RN_C_TIO in '..\enSoftPadrao\Regras\Oficina\OFI_RN_C_TIO.pas',
  OFI_RN_M_AGE in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_AGE.pas',
  OFI_RN_M_FEV in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_FEV.pas',
  OFI_RN_M_OCV in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_OCV.pas',
  OFI_RN_M_ORV in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_ORV.pas',
  OFI_RN_M_RQV in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_RQV.pas',
  CAD_RN_R_ALM in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_ALM.pas',
  CAD_RN_R_CCU in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_CCU.pas',
  CAD_RN_R_CFO in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_CFO.pas',
  CAD_RN_R_CID in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_CID.pas',
  CAD_RN_R_CNE in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_CNE.pas',
  CAD_RN_R_COR in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_COR.pas',
  CAD_RN_R_CRG in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_CRG.pas',
  CAD_RN_R_CTC in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_CTC.pas',
  CAD_RN_R_GRU in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_GRU.pas',
  CAD_RN_R_INF in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_INF.pas',
  CAD_RN_R_LTO in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_LTO.pas',
  CAD_RN_R_NCM in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_NCM.pas',
  CAD_RN_R_PCT in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_PCT.pas',
  CAD_RN_R_PEC in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_PEC.pas',
  CAD_RN_R_SET in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_SET.pas',
  CAD_RN_R_TAM in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_TAM.pas',
  CAD_RN_R_TDF in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_TDF.pas',
  CAD_RN_R_TIF in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_TIF.pas',
  CAD_RN_R_TRI in '..\enSoftPadrao\Regras\Relatórios\CAD_RN_R_TRI.pas',
  EST_RN_R_CTE in '..\enSoftPadrao\Regras\Relatórios\EST_RN_R_CTE.pas',
  EST_RN_R_DEV in '..\enSoftPadrao\Regras\Relatórios\EST_RN_R_DEV.pas',
  EST_RN_R_FIC in '..\enSoftPadrao\Regras\Relatórios\EST_RN_R_FIC.pas',
  EST_RN_R_GIR in '..\enSoftPadrao\Regras\Relatórios\EST_RN_R_GIR.pas',
  EST_RN_R_INV in '..\enSoftPadrao\Regras\Relatórios\EST_RN_R_INV.pas',
  FAT_RN_R_PIC in '..\enSoftPadrao\Regras\Relatórios\FAT_RN_R_PIC.pas',
  FAT_RN_R_POS in '..\enSoftPadrao\Regras\Relatórios\FAT_RN_R_POS.pas',
  FAT_RN_R_PPC in '..\enSoftPadrao\Regras\Relatórios\FAT_RN_R_PPC.pas',
  FIN_RN_R_PAG in '..\enSoftPadrao\Regras\Relatórios\FIN_RN_R_PAG.pas',
  OFI_RN_R_TIO in '..\enSoftPadrao\Regras\Relatórios\OFI_RN_R_TIO.pas',
  PCP_RN_C_CDP in '..\enSoftPadrao\Regras\Spuma\PCP_RN_C_CDP.pas',
  PCP_RN_M_ACR in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_ACR.pas',
  PCP_RN_M_IQF in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_IQF.pas',
  PCP_RN_M_ORS in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_ORS.pas',
  PCP_RN_M_ORS_ITE in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_ORS_ITE.pas',
  PCP_RN_M_RAA in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_RAA.pas',
  PCP_RN_M_ROM in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_ROM.pas',
  FIN_UN_M_BOL in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_BOL.pas' {FIN_FM_M_BOL},
  FIN_UN_M_CAR in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CAR.pas' {FIN_FM_M_CAR},
  FIN_UN_M_CHE_LAN in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CHE_LAN.pas' {FIN_FM_M_CHE_LAN},
  FIN_UN_M_CHE_MOV in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CHE_MOV.pas' {FIN_FM_M_CHE_MOV},
  FIN_UN_M_COB in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_COB.pas' {FIN_FM_M_COB},
  FIN_UN_M_CTA_ABE in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CTA_ABE.pas' {FIN_FM_M_CTA_ABE},
  FIN_UN_M_CTA_BCO in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CTA_BCO.pas' {FIN_FM_M_CTA_BCO},
  FIN_UN_M_CTA_CON in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CTA_CON.pas' {FIN_FM_M_CTA_CON},
  FIN_UN_M_CTA_CXA in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CTA_CXA.pas' {FIN_FM_M_CTA_CXA},
  FIN_UN_M_ORC in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_ORC.pas' {FIN_FM_M_ORC},
  FIN_UN_M_PAG in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_PAG.pas' {FIN_FM_M_PAG},
  FIN_UN_M_PBX in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_PBX.pas' {FIN_FM_M_PBX},
  FIN_UN_M_PQD in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_PQD.pas' {FIN_FM_M_PQD},
  FIN_UN_M_RBX in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_RBX.pas' {FIN_FM_M_RBX},
  FIN_UN_M_RCR in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_RCR.pas' {FIN_FM_M_RCR},
  FIN_UN_M_REC in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_REC.pas' {FIN_FM_M_REC},
  FIN_UN_M_REC_REM in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_REC_REM.pas' {FIN_FM_M_REC_REM},
  PSQ_UN_X_ALM in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ALM.pas' {PSQ_FM_X_ALM},
  PSQ_UN_X_CFO in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CFO.pas' {PSQ_FM_X_CFO},
  PSQ_UN_X_CID in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CID.pas' {PSQ_FM_X_CID},
  PSQ_UN_X_CLI in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CLI.pas' {PSQ_FM_X_CLI},
  PSQ_UN_X_CNE in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CNE.pas' {PSQ_FM_X_CNE},
  PSQ_UN_X_CNF in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CNF.pas' {PSQ_FM_X_CNF},
  PSQ_UN_X_COR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_COR.pas' {PSQ_FM_X_COR},
  PSQ_UN_X_CPG in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CPG.pas' {PSQ_FM_X_CPG},
  PSQ_UN_X_CRG in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CRG.pas' {PSQ_FM_X_CRG},
  PSQ_UN_X_CTA_BCO in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CTA_BCO.pas' {PSQ_FM_X_CTA_BCO},
  PSQ_UN_X_CTC in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CTC.pas' {PSQ_FM_X_CTC},
  PSQ_UN_X_DIS in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_DIS.pas' {PSQ_FM_X_DIS},
  PSQ_UN_X_EPI in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_EPI.pas' {PSQ_FM_X_EPI},
  PSQ_UN_X_ESP in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ESP.pas' {PSQ_FM_X_ESP},
  PSQ_UN_X_ETQ in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ETQ.pas' {PSQ_FM_X_ETQ},
  PSQ_UN_X_FOR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_FOR.pas' {PSQ_FM_X_FOR},
  PSQ_UN_X_FPG in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_FPG.pas' {PSQ_FM_X_FPG},
  PSQ_UN_X_FUN in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_FUN.pas' {PSQ_FM_X_FUN},
  PSQ_UN_X_GRU in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_GRU.pas' {PSQ_FM_X_GRU},
  PSQ_UN_X_INF in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_INF.pas' {PSQ_FM_X_INF},
  PSQ_UN_X_INS in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_INS.pas' {PSQ_FM_X_INS},
  PSQ_UN_X_ITE in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ITE.pas' {PSQ_FM_X_ITE},
  PSQ_UN_X_LME in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_LME.pas' {PSQ_FM_X_LME},
  PSQ_UN_X_MEQ in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_MEQ.pas' {PSQ_FM_X_MEQ},
  PSQ_UN_X_NCM in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_NCM.pas' {PSQ_FM_X_NCM},
  PSQ_UN_X_NFE in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_NFE.pas' {PSQ_FM_X_NFE},
  PSQ_UN_X_NRA in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_NRA.pas' {PSQ_FM_X_NRA},
  PSQ_UN_X_OBR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_OBR.pas' {PSQ_FM_X_OBR},
  PSQ_UN_X_OPR_OPS in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_OPR_OPS.pas' {PSQ_FM_X_OPR_OPS},
  PSQ_UN_X_PAR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PAR.pas' {PSQ_FM_X_PAR},
  PSQ_UN_X_PBX_TIT in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PBX_TIT.pas' {PSQ_FM_X_PBX_TIT},
  PSQ_UN_X_PCT in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PCT.pas' {PSQ_FM_X_PCT},
  PSQ_UN_X_PEC in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PEC.pas' {PSQ_FM_X_PEC},
  PSQ_UN_X_PRG in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PRG.pas' {PSQ_FM_X_PRG},
  PSQ_UN_X_REC in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_REC.pas' {PSQ_FM_X_REC},
  PSQ_UN_X_REC_CHE in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_REC_CHE.pas' {PSQ_FM_X_REC_CHE},
  PSQ_UN_X_ROT in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ROT.pas' {PSQ_FM_X_ROT},
  PSQ_UN_X_RUA in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_RUA.pas' {PSQ_FM_X_RUA},
  PSQ_UN_X_SET in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_SET.pas' {PSQ_FM_X_SET},
  PSQ_UN_X_TAM in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_TAM.pas' {PSQ_FM_X_TAM},
  PSQ_UN_X_TDF in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_TDF.pas' {PSQ_FM_X_TDF},
  PSQ_UN_X_TIF in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_TIF.pas' {PSQ_FM_X_TIF},
  PSQ_UN_X_TME in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_TME.pas' {PSQ_FM_X_TME},
  PSQ_UN_X_TRI in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_TRI.pas' {PSQ_FM_X_TRI},
  PSQ_UN_X_UND in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_UND.pas' {PSQ_FM_X_UND},
  PSQ_UN_X_VEI in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_VEI.pas' {PSQ_FM_X_VEI},
  CAD_UN_C_ALM in '..\enSoftPadrao\Cadastros\CAD_UN_C_ALM.pas' {CAD_FM_C_ALM},
  CAD_UN_C_CCU in '..\enSoftPadrao\Cadastros\CAD_UN_C_CCU.pas' {CAD_FM_C_CCU},
  CAD_UN_C_CFO in '..\enSoftPadrao\Cadastros\CAD_UN_C_CFO.pas' {CAD_FM_C_CFO},
  CAD_UN_C_CID in '..\enSoftPadrao\Cadastros\CAD_UN_C_CID.pas' {CAD_FM_C_CID},
  CAD_UN_C_CIN in '..\enSoftPadrao\Cadastros\CAD_UN_C_CIN.pas' {CAD_FM_C_CIN},
  CAD_UN_C_CLI in '..\enSoftPadrao\Cadastros\CAD_UN_C_CLI.pas' {CAD_FM_C_CLI},
  CAD_UN_C_CNE in '..\enSoftPadrao\Cadastros\CAD_UN_C_CNE.pas' {CAD_FM_C_CNE},
  CAD_UN_C_COR in '..\enSoftPadrao\Cadastros\CAD_UN_C_COR.pas' {CAD_FM_C_COR},
  CAD_UN_C_CPG in '..\enSoftPadrao\Cadastros\CAD_UN_C_CPG.pas' {CAD_FM_C_CPG},
  CAD_UN_C_CTC in '..\enSoftPadrao\Cadastros\CAD_UN_C_CTC.pas' {CAD_FM_C_CTC},
  CAD_UN_C_ECF in '..\enSoftPadrao\Cadastros\CAD_UN_C_ECF.pas' {CAD_FM_C_ECF},
  CAD_UN_C_FOR in '..\enSoftPadrao\Cadastros\CAD_UN_C_FOR.pas' {CAD_FM_C_FOR},
  CAD_UN_C_FPG in '..\enSoftPadrao\Cadastros\CAD_UN_C_FPG.pas' {CAD_FM_C_FPG},
  CAD_UN_C_FUN in '..\enSoftPadrao\Cadastros\CAD_UN_C_FUN.pas' {CAD_FM_C_FUN},
  CAD_UN_C_GRU in '..\enSoftPadrao\Cadastros\CAD_UN_C_GRU.pas' {CAD_FM_C_GRU},
  CAD_UN_C_INF in '..\enSoftPadrao\Cadastros\CAD_UN_C_INF.pas' {CAD_FM_C_INF},
  CAD_UN_C_ITE in '..\enSoftPadrao\Cadastros\CAD_UN_C_ITE.pas' {CAD_FM_C_ITE},
  CAD_UN_C_LTO in '..\enSoftPadrao\Cadastros\CAD_UN_C_LTO.pas' {CAD_FM_C_LTO},
  CAD_UN_C_MVE in '..\enSoftPadrao\Cadastros\CAD_UN_C_MVE.pas' {CAD_FM_C_MVE},
  CAD_UN_C_NAT in '..\enSoftPadrao\Cadastros\CAD_UN_C_NAT.pas' {CAD_FM_C_NAT},
  CAD_UN_C_NCM in '..\enSoftPadrao\Cadastros\CAD_UN_C_NCM.pas' {CAD_FM_C_NCM},
  CAD_UN_C_PAR in '..\enSoftPadrao\Cadastros\CAD_UN_C_PAR.pas' {CAD_FM_C_PAR},
  CAD_UN_C_PCT in '..\enSoftPadrao\Cadastros\CAD_UN_C_PCT.pas' {CAD_FM_C_PCT},
  CAD_UN_C_PEC in '..\enSoftPadrao\Cadastros\CAD_UN_C_PEC.pas' {CAD_FM_C_PEC},
  CAD_UN_C_RAM in '..\enSoftPadrao\Cadastros\CAD_UN_C_RAM.pas' {CAD_FM_C_RAM},
  PCP_UN_C_CRG in '..\enSoftSpuma\Cadastros\PCP_UN_C_CRG.pas' {PCP_FM_C_CRG},
  CMP_UN_M_APR in '..\enSoftPadrao\Movimentacoes\Compras\CMP_UN_M_APR.pas' {CMP_FM_M_APR},
  CMP_UN_M_COT in '..\enSoftPadrao\Movimentacoes\Compras\CMP_UN_M_COT.pas' {CMP_FM_M_COT},
  CMP_UN_M_COT_ISC in '..\enSoftPadrao\Movimentacoes\Compras\CMP_UN_M_COT_ISC.pas' {CMP_FM_M_COT_ISC},
  CMP_UN_M_PED in '..\enSoftPadrao\Movimentacoes\Compras\CMP_UN_M_PED.pas' {CMP_FM_M_PED},
  CMP_UN_M_SOL in '..\enSoftPadrao\Movimentacoes\Compras\CMP_UN_M_SOL.pas' {CMP_FM_M_SOL},
  CMP_UN_M_XML in '..\enSoftPadrao\Movimentacoes\Compras\CMP_UN_M_XML.pas' {CMP_FM_M_XML},
  FAT_UN_M_CXA in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA.pas' {FAT_FM_M_CXA},
  FAT_UN_M_CXA_NFE in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE.pas' {FAT_FM_M_CXA_NFE},
  FAT_UN_M_FAT in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_FAT.pas' {FAT_FM_M_FAT},
  FAT_UN_M_IQM in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_IQM.pas' {FAT_FM_M_IQM},
  FAT_UN_M_IQM_ITE_ANA in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_IQM_ITE_ANA.pas' {FAT_FM_M_IQM_ITE_ANA},
  FAT_UN_M_NFE_ANA in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_NFE_ANA.pas' {FAT_FM_M_NFE_ANA},
  FAT_UN_M_NFE_FRE in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_NFE_FRE.pas' {FAT_FM_M_NFE_FRE},
  FAT_UN_M_NFE_IQM in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_NFE_IQM.pas' {FAT_FM_M_NFE_IQM},
  EST_UN_M_CTE in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_CTE.pas' {EST_FM_M_CTE},
  EST_UN_M_MAL in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_MAL.pas' {EST_FM_M_MAL},
  EST_UN_M_NFC in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_NFC.pas' {EST_FM_M_NFC},
  EST_UN_M_NFD in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_NFD.pas' {EST_FM_M_NFD},
  EST_UN_M_NFE in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_NFE.pas',
  EST_UN_M_NFE_TIT in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_NFE_TIT.pas',
  EST_UN_M_NFS in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_NFS.pas',
  FAT_UN_M_NFE_IPE in '..\enSoftPadrao\Movimentacoes\Estoque\FAT_UN_M_NFE_IPE.pas' {FAT_FM_M_NFE_IPE},
  FAT_UN_M_NFE_IPQ in '..\enSoftPadrao\Movimentacoes\Estoque\FAT_UN_M_NFE_IPQ.pas' {FAT_FM_M_NFE_IPQ},
  CAD_UN_C_FAM in '..\enSoftPadrao\Cadastros\CAD_UN_C_FAM.pas' {CAD_FM_C_FAM},
  PCP_UN_C_MDE in '..\enSoftSpuma\Cadastros\PCP_UN_C_MDE.pas' {PCP_FM_C_MDE},
  PCP_UN_M_ORS in '..\enSoftPadrao\Movimentacoes\PCP\PCP_UN_M_ORS.pas' {PCP_FM_M_ORS},
  PCP_UN_M_ROM in '..\enSoftPadrao\Movimentacoes\PCP\PCP_UN_M_ROM.pas' {PCP_FM_M_ROM},
  CAD_UN_C_VEI in '..\enSoftPadrao\Cadastros\CAD_UN_C_VEI.pas' {CAD_FM_C_VEI},
  PAD_UN_X_FRM in '..\enSoftPadrao\Padrao\PAD_UN_X_FRM.pas' {PAD_FM_X_FRM},
  ufrmStatus in '..\enSoftPadrao\Padrao\ufrmStatus.pas' {frmStatus},
  CSU_UN_C_CLI in '..\enSoftPadrao\Estatistica\CSU_UN_C_CLI.pas' {CSU_FM_C_CLI},
  CSU_UN_C_CLI_FIN in '..\enSoftPadrao\Estatistica\CSU_UN_C_CLI_FIN.pas' {CSU_FM_C_CLI_FIN},
  CSU_UN_C_CLI_NFE in '..\enSoftPadrao\Estatistica\CSU_UN_C_CLI_NFE.pas' {CSU_FM_C_CLI_NFE},
  CSU_UN_C_CLI_STA in '..\enSoftPadrao\Estatistica\CSU_UN_C_CLI_STA.pas' {CSU_FM_C_CLI_STA},
  CSU_UN_C_FOR in '..\enSoftPadrao\Estatistica\CSU_UN_C_FOR.pas' {CSU_FM_C_FOR},
  CSU_UN_C_FOR_FIN in '..\enSoftPadrao\Estatistica\CSU_UN_C_FOR_FIN.pas' {CSU_FM_C_FOR_FIN},
  CSU_UN_C_FOR_NFE in '..\enSoftPadrao\Estatistica\CSU_UN_C_FOR_NFE.pas' {CSU_FM_C_FOR_NFE},
  CSU_UN_C_FOR_STA in '..\enSoftPadrao\Estatistica\CSU_UN_C_FOR_STA.pas' {CSU_FM_C_FOR_STA},
  CSU_UN_C_ITE in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE.pas' {CSU_FM_C_ITE},
  CSU_UN_C_ITE_EST in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE_EST.pas' {CSU_FM_C_ITE_EST},
  CSU_UN_C_ITE_EXT in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE_EXT.pas' {CSU_FM_C_ITE_EXT},
  CSU_UN_C_ITE_NFE in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE_NFE.pas' {CSU_FM_C_ITE_NFE},
  CSU_UN_M_PED in '..\enSoftPadrao\Estatistica\CSU_UN_M_PED.pas' {CSU_FM_M_PED},
  CSU_UN_M_PSC in '..\enSoftPadrao\Estatistica\CSU_UN_M_PSC.pas' {CSU_FM_M_PSC},
  CAD_UN_C_SET in '..\enSoftPadrao\Cadastros\Tabelas\CAD_UN_C_SET.pas' {CAD_FM_C_SET},
  PCP_UN_M_CME in '..\enSoftPadrao\Movimentacoes\Manutenção\PCP_UN_M_CME.pas' {PCP_FM_M_CME},
  PCP_UN_M_MCP in '..\enSoftPadrao\Movimentacoes\Manutenção\PCP_UN_M_MCP.pas' {PCP_FM_M_MCP},
  PCP_RN_M_CRP in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_CRP.pas',
  EST_RN_M_MAL in '..\enSoftPadrao\Regras\Estoque\EST_RN_M_MAL.pas',
  FAT_UN_M_CXA_MPS in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_MPS.pas' {FAT_FM_M_CXA_MPS},
  FAT_UN_M_CXA_NFE_TRA in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_TRA.pas' {FAT_FM_M_CXA_NFE_TRA},
  FAT_UN_M_POS in '..\enSoftPadrao\Movimentacoes\Comercial\FAT_UN_M_POS.pas' {FAT_FM_M_POS},
  CAD_RN_C_PES in '..\enSoftPadrao\Regras\Cadastros\CAD_RN_C_PES.pas',
  CAD_UN_C_PES in '..\enSoftPadrao\Cadastros\CAD_UN_C_PES.pas' {CAD_FM_C_PES},
  CAD_RN_C_FPG in '..\enSoftPadrao\Regras\Cadastros\CAD_RN_C_FPG.pas',
  YMOFXReader in '..\enSoftPadrao\Biblioteca\YMOFXReader.pas',
  PSQ_UN_X_PED in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PED.pas' {PSQ_FM_X_PED},
  FAT_UN_M_CXA_NFE_FPG in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_FPG.pas' {FAT_FM_M_CXA_NFE_FPG},
  PSQ_UN_X_ORS in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ORS.pas' {PSQ_FM_X_ORS},
  FAT_RN_M_ROM in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_ROM.pas',
  CAD_UN_R_CCU in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CCU.pas' {CAD_FM_R_CCU},
  CAD_UN_R_CFO in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CFO.pas' {CAD_FM_R_CFO},
  CAD_UN_R_CID in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CID.pas' {CAD_FM_R_CID},
  CAD_UN_R_CLI in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CLI.pas' {CAD_FM_R_CLI},
  CAD_UN_R_CNE in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CNE.pas' {CAD_FM_R_CNE},
  CAD_UN_R_COR in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_COR.pas' {CAD_FM_R_COR},
  CAD_UN_R_CRG in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CRG.pas' {CAD_FM_R_CRG},
  CAD_UN_R_CTC in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_CTC.pas' {CAD_FM_R_CTC},
  CAD_UN_R_FOR in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_FOR.pas' {CAD_FM_R_FOR},
  CAD_UN_R_FPG in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_FPG.pas' {CAD_FM_R_FPG},
  CAD_UN_R_FUN in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_FUN.pas' {CAD_FM_R_FUN},
  CAD_UN_R_GRU in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_GRU.pas' {CAD_FM_R_GRU},
  CAD_UN_R_INF in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_INF.pas' {CAD_FM_R_INF},
  CAD_UN_R_ITE in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_ITE.pas' {CAD_FM_R_ITE},
  CAD_UN_R_NCM in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_NCM.pas' {CAD_FM_R_NCM},
  CAD_UN_R_RAM in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_RAM.pas' {CAD_FM_R_RAM},
  CAD_UN_R_E01 in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_E01.pas' {CAD_FM_R_E01},
  CAD_UN_R_LTO in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_LTO.pas' {CAD_FM_R_LTO},
  CAD_UN_R_MVE in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_MVE.pas' {CAD_FM_R_MVE},
  CAD_UN_R_PCT in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_PCT.pas' {CAD_FM_R_PCT},
  CAD_UN_R_PEC in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_PEC.pas' {CAD_FM_R_PEC},
  CAD_UN_R_PES in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_PES.pas' {CAD_FM_R_PES},
  CAD_UN_R_PRG in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_PRG.pas' {CAD_FM_R_PRG},
  CAD_UN_R_SET in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_SET.pas' {CAD_FM_R_SET},
  CAD_UN_R_TAM in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_TAM.pas' {CAD_FM_R_TAM},
  CAD_UN_R_TDF in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_TDF.pas' {CAD_FM_R_TDF},
  CAD_UN_R_TIF in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_TIF.pas' {CAD_FM_R_TIF},
  CAD_UN_R_TME in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_TME.pas' {CAD_FM_R_TME},
  CAD_UN_R_TRI in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_TRI.pas' {CAD_FM_R_TRI},
  CAD_UN_R_UND in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_UND.pas' {CAD_FM_R_UND},
  OFI_UN_R_TIO in '..\enSoftPadrao\Relatorios\Cadastros\OFI_UN_R_TIO.pas' {OFI_FM_R_TIO},
  FAT_UN_M_CXA_NFE_MAQ in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_MAQ.pas' {FAT_FM_M_CXA_NFE_MAQ},
  CSU_UN_M_COB in '..\enSoftPadrao\Estatistica\CSU_UN_M_COB.pas' {CSU_FM_M_COB},
  FAT_UN_M_PED in '..\enSoftPadrao\Movimentacoes\Comercial\FAT_UN_M_PED.pas' {FAT_FM_M_PED},
  FAT_UN_M_PED_IOR in '..\enSoftPadrao\Movimentacoes\Comercial\FAT_UN_M_PED_IOR.pas' {FAT_FM_M_PED_IOR},
  OFI_RN_M_POS in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_POS.pas',
  CTC_RN_C_SER in '..\enSoftPadrao\Regras\Cadastros\CTC_RN_C_SER.pas',
  PSQ_UN_X_SER in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_SER.pas' {PSQ_FM_X_SER},
  FIN_RN_M_CTA_CON in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CTA_CON.pas',
  CAD_UN_C_FUN_RDF in '..\enSoftPadrao\Cadastros\CAD_UN_C_FUN_RDF.pas' {CAD_FM_C_FUN_RDF},
  CTC_RN_C_TPR in '..\enSoftPadrao\Regras\Cadastros\CTC_RN_C_TPR.pas',
  CTC_RN_M_ORC in '..\enSoftPadrao\Regras\Cadastros\CTC_RN_M_ORC.pas',
  CTC_UN_M_ORC in 'Movimentacoes\Engenharia\CTC_UN_M_ORC.pas' {CTC_FM_M_ORC},
  CTC_UN_C_EOC in '..\enSoftPadrao\Movimentacoes\CTC\CTC_UN_C_EOC.pas' {CTC_FM_C_EOC},
  CTC_RN_C_EOC in '..\enSoftPadrao\Regras\Cadastros\CTC_RN_C_EOC.pas',
  PSQ_UN_X_TPR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_TPR.pas' {PSQ_FM_X_TPR},
  CTC_UN_R_ORC in '..\enSoftPadrao\Relatorios\Movimentações\CTC_UN_R_ORC.pas' {CTC_FM_R_ORC},
  CTC_UN_R_COM in '..\enSoftPadrao\Relatorios\Movimentações\CTC_UN_R_COM.pas' {CTC_FM_R_COM},
  CTC_UN_M_MED in '..\enSoftPadrao\Movimentacoes\CTC\CTC_UN_M_MED.pas' {CTC_FM_M_MED},
  FAT_UN_M_IQM_IMP in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_IQM_IMP.pas' {FAT_FM_M_IQM_IMP},
  CTC_RN_M_MED in '..\enSoftPadrao\Regras\Cadastros\CTC_RN_M_MED.pas',
  CTC_UN_R_MED in '..\enSoftPadrao\Relatorios\Movimentações\CTC_UN_R_MED.pas' {CTC_FM_R_MED},
  Unit1 in '..\enSoftPadrao\Padrao\Unit1.pas' {frmNFCe},
  EST_UN_R_FIC in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_FIC.pas' {EST_FM_R_FIC},
  EST_UN_R_DEV in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_DEV.pas' {EST_FM_R_DEV},
  EST_UN_R_ABC in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_ABC.pas' {EST_FM_R_ABC},
  EST_UN_R_INV in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_INV.pas' {EST_FM_R_INV},
  EST_UN_R_CTE in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_CTE.pas' {EST_FM_R_CTE},
  EST_UN_R_GIR in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_GIR.pas' {EST_FM_R_GIR},
  EST_UN_R_MOV in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_MOV.pas' {EST_FM_R_MOV},
  EST_RN_R_ABC in '..\enSoftPadrao\Regras\Relatórios\EST_RN_R_ABC.pas',
  FIN_UN_R_PAG in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_PAG.pas' {FIN_FM_R_PAG},
  FIN_UN_R_PCP in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_PCP.pas' {FIN_FM_R_PCP},
  FIN_UN_R_EXF in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_EXF.pas' {FIN_FM_R_EXF},
  FIN_UN_R_REC in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_REC.pas' {FIN_FM_R_REC},
  FIN_UN_R_PCR in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_PCR.pas' {FIN_FM_R_PCR},
  FIN_UN_R_EXC in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_EXC.pas' {FIN_FM_R_EXC},
  FIN_UN_R_COB in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_COB.pas' {FIN_FM_R_COB},
  FIN_UN_R_MCH in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_MCH.pas' {FIN_FM_R_MCH},
  FIN_UN_R_CHQ in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_CHQ.pas' {FIN_FM_R_CHQ},
  FIN_UN_R_CXA in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_CXA.pas' {FIN_FM_R_CXA},
  FIN_UN_R_BCO in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_BCO.pas' {FIN_FM_R_BCO},
  FIN_UN_R_ANV in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_ANV.pas' {FIN_FM_R_ANV},
  uDmCtc in '..\enSoftPadrao\DataModule\uDmCtc.pas' {dmCtc: TDataModule},
  uDmSgq in '..\enSoftPadrao\DataModule\uDmSgq.pas' {dmSgq: TDataModule},
  FIN_UN_M_PCR in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_PCR.pas' {FIN_FM_M_PCR},
  FAT_UN_M_PED_RTC in '..\enSoftPadrao\Movimentacoes\Comercial\FAT_UN_M_PED_RTC.pas' {FAT_FM_M_PED_RTC},
  FIN_RN_M_CBX in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_CBX.pas',
  EST_RN_M_MET in '..\enSoftPadrao\Regras\Estoque\EST_RN_M_MET.pas',
  CSU_UN_C_CLI_FIN_ITE in '..\enSoftPadrao\Estatistica\CSU_UN_C_CLI_FIN_ITE.pas' {CSU_FM_C_CLI_FIN_ITE},
  PSQ_UN_X_CTE in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CTE.pas' {PSQ_FM_X_CTE},
  FIN_UN_M_REC_RET in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_REC_RET.pas' {FIN_FM_M_REC_RET},
  CSU_UN_M_NFE in '..\enSoftPadrao\Estatistica\CSU_UN_M_NFE.pas' {CSU_FM_M_NFE},
  FAT_RN_M_XML in '..\enSoftPadrao\Regras\Faturamento\FAT_RN_M_XML.pas',
  FAT_UN_M_CXA_RBX in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_RBX.pas' {FAT_FM_M_CXA_RBX},
  EST_UN_M_XML in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_XML.pas' {EST_FM_M_XML},
  FAT_UN_M_CXA_NFE_NCF in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_NCF.pas' {FAT_FM_M_CXA_NFE_NCF},
  CTC_UN_M_PRO in 'Movimentacoes\Qualidade\CTC_UN_M_PRO.pas' {CTC_FM_M_PRO},
  CTC_RN_M_PRO in '..\enSoftPadrao\Regras\Cadastros\CTC_RN_M_PRO.pas',
  CSU_UN_M_ORC in '..\enSoftPadrao\Estatistica\CSU_UN_M_ORC.pas' {CSU_FM_M_ORC},
  CTC_UN_M_APG in '..\enSoftPadrao\Movimentacoes\Financeiro\CTC_UN_M_APG.pas' {CTC_FM_M_APG},
  CTC_RN_M_APG in '..\enSoftPadrao\Regras\Financeiro\CTC_RN_M_APG.pas',
  CTC_UN_M_SLM in 'Movimentacoes\Manutencao\CTC_UN_M_SLM.pas' {CTC_FM_M_SLM},
  CTC_UN_R_SLM in '..\enSoftPadrao\Relatorios\Movimentações\CTC_UN_R_SLM.pas' {CTC_FM_R_SLM},
  CTC_RN_M_SLM in '..\enSoftPadrao\Regras\Estoque\CTC_RN_M_SLM.pas',
  FAT_UN_M_LIB in '..\enSoftPadrao\Movimentacoes\Comercial\FAT_UN_M_LIB.pas' {FAT_FM_M_LIB},
  FIN_UN_M_CTA_REA in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_CTA_REA.pas' {FIN_FM_M_CTA_REA},
  FAT_UN_M_CXA_NFE_IMP in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_IMP.pas' {FAT_FM_M_CXA_NFE_IMP},
  FAT_UN_M_ROM in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_ROM.pas' {FAT_FM_M_ROM},
  FAT_UN_M_MDF in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_MDF.pas' {FAT_FM_M_MDF},
  FAT_UN_M_MDF_STA in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_MDF_STA.pas' {FAT_FM_MDF_STA},
  FAT_UN_M_ROM_PCA in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_ROM_PCA.pas' {FAT_FM_M_ROM_PCA},
  PCP_UN_M_ROM_COF in '..\enSoftPadrao\Movimentacoes\PCP\PCP_UN_M_ROM_COF.pas' {PCP_FM_M_ROM_COF},
  PCP_RN_C_FPI in '..\enSoftPadrao\Regras\Spuma\PCP_RN_C_FPI.pas',
  PCP_UN_M_ROM_COF_ETQ in '..\enSoftPadrao\Movimentacoes\PCP\PCP_UN_M_ROM_COF_ETQ.pas' {PCP_FM_M_ROM_COF_ETQ},
  FAT_UN_M_CXA_NFE_CAN in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_CAN.pas' {FAT_FM_M_CXA_NFE_CAN},
  PCP_RN_M_OPR in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_OPR.pas',
  PCP_RN_M_OPR_REQ in '..\enSoftPadrao\Regras\Spuma\PCP_RN_M_OPR_REQ.pas',
  AVS_UN_X_EST in '..\enSoftPadrao\Alertas\AVS_UN_X_EST.pas' {AVS_FM_X_EST},
  AVS_UN_X_APG in '..\enSoftPadrao\Alertas\AVS_UN_X_APG.pas' {AVS_FM_X_APG},
  FIN_UN_M_PDE in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_PDE.pas' {FIN_FM_M_PDE},
  PSQ_UN_X_PAI in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PAI.pas' {PSQ_FM_X_PAI},
  EST_UN_M_MAL_COF in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_MAL_COF.pas' {EST_FM_M_MAL_COF},
  PSQ_UN_X_ROM_ETQ in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_ROM_ETQ.pas' {PSQ_FM_X_ROM_ETQ},
  FAT_UN_M_CXA_NFE_CRT in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_CXA_NFE_CRT.pas' {FAT_FM_M_CXA_NFE_CRT},
  CAD_UN_R_FAM in '..\enSoftPadrao\Relatorios\Cadastros\CAD_UN_R_FAM.pas' {CAD_FM_R_FAM},
  FAT_UN_R_NFE in '..\enSoftPadrao\Relatorios\Movimentações\FAT_UN_R_NFE.pas' {FAT_FM_R_NFE},
  FAT_RN_R_NFE in '..\enSoftPadrao\Regras\Relatórios\FAT_RN_R_NFE.pas',
  CTC_UN_C_OCO in 'Cadastros\CTC_UN_C_OCO.pas' {CTC_FM_C_OCO},
  CTC_RN_C_OCO in '..\enSoftPadrao\Regras\Build\CTC_RN_C_OCO.pas',
  CSU_UN_C_ITE_CMP in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE_CMP.pas' {CSU_FM_C_ITE_CMP},
  PSQ_UN_X_GRP in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_GRP.pas' {PSQ_FM_X_GRP},
  CSU_UN_C_ITE_ORV in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE_ORV.pas' {CSU_FM_C_ITE_ORV},
  FIN_RN_M_LMF in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_LMF.pas',
  FIN_RN_M_PCR in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_PCR.pas',
  FIN_RN_M_PRC in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_PRC.pas',
  FIN_UN_M_LMF in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_LMF.pas' {FIN_FM_M_LMF},
  FIN_UN_M_PRC in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_PRC.pas' {FIN_FM_M_PRC},
  FIN_UN_R_LMF in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_LMF.pas' {FIN_FM_R_LMF},
  FIN_UN_R_PRC in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_PRC.pas' {FIN_FM_R_PRC},
  PSQ_UN_X_LMF in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_LMF.pas' {PSQ_FM_X_LMF},
  EST_UN_M_NFS_CPM in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_NFS_CPM.pas' {EST_FM_M_NFS_CPM},
  CAD_UN_C_DTS in '..\enSoftPadrao\Cadastros\CAD_UN_C_DTS.pas' {CAD_FM_C_DTS},
  CTC_UN_M_PME in 'Movimentacoes\Manutencao\CTC_UN_M_PME.pas' {CTC_FM_M_PME},
  CTC_RN_M_PME in '..\enSoftPadrao\Regras\Build\CTC_RN_M_PME.pas',
  PSQ_UN_X_RBX_TIT in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_RBX_TIT.pas' {PSQ_FM_X_RBX_TIT},
  FIN_UN_R_OBR in '..\enSoftPadrao\Relatorios\Movimentações\FIN_UN_R_OBR.pas' {FIN_FM_R_OBR},
  FIN_RN_M_DCT in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_DCT.pas',
  PSQ_UN_X_MTA in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_MTA.pas' {PSQ_FM_X_MTA},
  CAD_UN_C_AUS in '..\enSoftPadrao\Cadastros\CAD_UN_C_AUS.pas' {CAD_FM_C_AUS},
  CAD_RN_C_AUS in '..\enSoftPadrao\Regras\Cadastros\CAD_RN_C_AUS.pas',
  CAD_UN_C_CLI_PRO in '..\enSoftPadrao\Cadastros\CAD_UN_C_CLI_PRO.pas' {CAD_FM_C_CLI_PRO},
  PSQ_UN_X_CUL in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CUL.pas' {PSQ_FM_X_CUL},
  PSQ_UN_X_RVD in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_RVD.pas' {PSQ_FM_X_RVD},
  CSU_UN_C_ITE_COJ in '..\enSoftPadrao\Estatistica\CSU_UN_C_ITE_COJ.pas' {CSU_FM_C_ITE_COJ},
  FIN_UN_M_MCH in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_MCH.pas' {FIN_FM_M_MCH},
  FIN_UN_M_MCH_FIL in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_MCH_FIL.pas' {FIN_FM_M_MCH_FIL},
  FIN_UN_M_MCH_PGT in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_MCH_PGT.pas' {FIN_FM_M_MCH_PGT},
  EST_UN_R_MAL in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_MAL.pas' {EST_FM_R_MAL},
  PCP_UN_C_MEQ in '..\enSoftPadrao\Cadastros\PCP_UN_C_MEQ.pas' {PCP_FM_C_MEQ},
  uNfse in '..\enSoftPadrao\Padrao\uNfse.pas' {frmNFSe},
  PSQ_UN_X_CXA in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_CXA.pas' {PSQ_FM_X_CXA},
  CSU_UN_M_GPS in '..\enSoftPadrao\Estatistica\CSU_UN_M_GPS.pas' {CSU_FM_M_GPS},
  CSU_UN_M_VPR_ROT in '..\enSoftPadrao\Estatistica\CSU_UN_M_VPR_ROT.pas' {CSU_FM_M_VPR_ROT},
  CSU_UN_M_AUD in '..\enSoftPadrao\Estatistica\CSU_UN_M_AUD.pas' {CSU_FM_M_AUD},
  CSU_UN_M_AUD_XML in '..\enSoftPadrao\Estatistica\CSU_UN_M_AUD_XML.pas' {CSU_FM_M_AUD_XML},
  PSQ_UN_X_PRO in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_PRO.pas' {PSQ_FM_X_PRO},
  PCP_RN_C_REG in '..\enSoftPadrao\Regras\Spuma\PCP_RN_C_REG.pas',
  FAT_UN_M_PED_SEN in '..\enSoftPadrao\Movimentacoes\Faturamento\FAT_UN_M_PED_SEN.pas' {FAT_FM_M_PED_SEN},
  EST_UN_R_DEZ in '..\enSoftPadrao\Relatorios\Movimentações\EST_UN_R_DEZ.pas' {EST_FM_R_DEZ},
  FormImg in '..\enSoftPadrao\Padrao\FormImg.pas' {FImg},
  AVS_UN_X_SOL in '..\enSoftPadrao\Alertas\AVS_UN_X_SOL.pas' {AVS_FM_X_SOL},
  FAT_UN_R_POS in '..\enSoftPadrao\Relatorios\Movimentações\FAT_UN_R_POS.pas' {FAT_FM_R_POS},
  OFI_UN_M_ORP in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_ORP.pas' {OFI_FM_M_ORP},
  OFI_UN_M_ORP_SUB in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_ORP_SUB.pas' {OFI_FM_M_ORP_SUB},
  OFI_UN_M_RPP in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_RPP.pas' {OFI_FM_M_RPP},
  OFI_UN_M_RPP_CAN in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_RPP_CAN.pas' {OFI_FM_M_RPP_CAN},
  OFI_UN_M_RPP_IMP in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_RPP_IMP.pas' {OFI_FM_M_RPP_IMP},
  OFI_UN_M_FEP in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_FEP.pas' {OFI_FM_M_FEP},
  OFI_UN_M_FEV_OPC in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_FEV_OPC.pas' {OFI_FM_M_FEV_OPC},
  OFI_UN_M_ORP_CAN in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_ORP_CAN.pas' {OFI_FM_M_ORP_CAN},
  OFI_UN_R_OFP_POS in '..\enSoftPadrao\Relatorios\Movimentações\OFI_UN_R_OFP_POS.pas' {OFI_FM_R_OFP_POS},
  OFI_UN_R_FIP in '..\enSoftPadrao\Relatorios\Movimentações\OFI_UN_R_FIP.pas' {OFI_FM_R_FIP},
  OFI_UN_R_HIP in '..\enSoftPadrao\Relatorios\Movimentações\OFI_UN_R_HIP.pas' {OFI_FM_R_HIP},
  PSQ_UN_X_MVE in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_MVE.pas' {PSQ_FM_X_MVE},
  PCP_UN_C_LME in '..\enSoftSpuma\Cadastros\PCP_UN_C_LME.pas' {PCP_FM_C_LME},
  PCP_UN_C_ORI in '..\enSoftSpuma\Cadastros\PCP_UN_C_ORI.pas' {PCP_FM_C_ORI},
  PCP_UN_C_TLM in '..\enSoftSpuma\Cadastros\PCP_UN_C_TLM.pas' {PCP_FM_C_TLM},
  CAD_UN_C_PRG in '..\enSoftPadrao\Cadastros\CAD_UN_C_PRG.pas' {CAD_FM_C_PRG},
  enFormBloq in '..\enSoftPadrao\Padrao\enFormBloq.pas' {frmBloq},
  OFI_UN_M_CVL in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_CVL.pas' {OFI_FM_M_CVL},
  OFI_UN_M_CVL_IMP in '..\enSoftPadrao\Movimentacoes\Oficina\OFI_UN_M_CVL_IMP.pas' {OFI_FM_M_CVL_IMP},
  OFI_RN_M_CVL in '..\enSoftPadrao\Regras\Oficina\OFI_RN_M_CVL.pas',
  EST_UN_M_XML_LOT in '..\enSoftPadrao\Movimentacoes\Estoque\EST_UN_M_XML_LOT.pas' {EST_FM_M_XML_LOT},
  FIN_UN_M_BRD in '..\enSoftPadrao\Movimentacoes\Financeiro\FIN_UN_M_BRD.pas' {FIN_FM_M_BRD},
  FIN_RN_M_BRD in '..\enSoftPadrao\Regras\Financeiro\FIN_RN_M_BRD.pas',
  PSQ_UN_X_MAR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_MAR.pas' {PSQ_FM_X_MAR},
  PSQ_UN_X_NTR in '..\enSoftPadrao\Cadastros\Consultas\PSQ_UN_X_NTR.pas' {PSQ_FM_X_NTR};

{$R *.res}

begin
   Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TSEG_FM_X_SEN, SEG_FM_X_SEN);
  Application.CreateForm(TdmGeral, dmGeral);
  Application.CreateForm(TdmCtc, dmCtc);
  Application.CreateForm(TdmSgq, dmSgq);
  if SEG_FM_X_SEN.ShowModal = mrOK then
     begin
       FreeAndNil(SEG_FM_X_SEN);
       Application.CreateForm(TfrmSoftMenu, frmSoftMenu);
       Application.Run;
     end
  else
    begin
       dmGeral.Conexao.Connected := false;
       FreeAndNil(dmGeral);
       FreeAndNil(SEG_FM_X_SEN);
       Application.terminate;
    end;
end.
