// <auto-generated />
namespace enLoja.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class complementoTipos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(complementoTipos));
        
        string IMigrationMetadata.Id
        {
            get { return "201307112302025_complementoTipos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
